CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902120428_InitialCreate') THEN
    CREATE TABLE "Users" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(200) NOT NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902120428_InitialCreate') THEN
    CREATE TABLE "Tasks" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CreatedAt" timestamp with time zone NOT NULL,
        "RequiredByDate" date NOT NULL,
        "Description" character varying(2000) NOT NULL,
        "Status" character varying(50) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "AssignedToUserId" integer NOT NULL,
        "ModifiedAt" timestamp with time zone,
        "ModifiedBy" character varying(100),
        CONSTRAINT "PK_Tasks" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Tasks_Users_AssignedToUserId" FOREIGN KEY ("AssignedToUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902120428_InitialCreate') THEN
    CREATE TABLE "Comments" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "TaskItemId" integer NOT NULL,
        "DateAdded" timestamp with time zone NOT NULL,
        "Text" character varying(3000) NOT NULL,
        "Type" character varying(50) NOT NULL,
        "ReminderDate" date,
        "ModifiedAt" timestamp with time zone,
        "ModifiedBy" character varying(100),
        CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Comments_Tasks_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "Tasks" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902120428_InitialCreate') THEN
    INSERT INTO "Users" ("Id", "Name")
    VALUES (1, 'Anton');
    INSERT INTO "Users" ("Id", "Name")
    VALUES (2, 'Borislav');
    INSERT INTO "Users" ("Id", "Name")
    VALUES (3, 'Georgi');
    INSERT INTO "Users" ("Id", "Name")
    VALUES (4, 'Petur');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902120428_InitialCreate') THEN
    CREATE INDEX "IX_Comments_TaskItemId" ON "Comments" ("TaskItemId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902120428_InitialCreate') THEN
    CREATE INDEX "IX_Tasks_AssignedToUserId" ON "Tasks" ("AssignedToUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902120428_InitialCreate') THEN
    PERFORM setval(
        pg_get_serial_sequence('"Users"', 'Id'),
        GREATEST(
            (SELECT MAX("Id") FROM "Users") + 1,
            nextval(pg_get_serial_sequence('"Users"', 'Id'))),
        false);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260902120428_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260902120428_InitialCreate', '10.0.4');
    END IF;
END $EF$;
COMMIT;

